# Global
permalink:           none
timezone:            'Europe/Amsterdam'

# Setup
title:               Alan Qiu
tagline:             'A Programmer'
description:         'A Programmer'
url:                 https://alanjqiu.github.io
baseurl:             ''
markdown:            kramdown
kramdown:
  input:             GFM
pygements:           true
exclude:             ['Rakefile.rb', 'CNAME', 'README.md', 'vendor']
github:
  repo:              https://github.com/alanjqiu/alanjqiu.github.io

# About/contact
author:
  name:              Alan Qiu
  url:               https://github.com/alanjqiu
  email:             alanjqiu@gmail.com

# Custom vars
version:             1.3.0
