# Permalinks
permalink:           pretty

# Setup
title:               Alan Qiu
tagline:             'A Programmer'
description:         'A Programmer'
url:                 https://alan-qiu.github.io
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
markdown:            kramdown
kramdown:
  input:             GFM
pygements:           true
exclude:             ['Rakefile.rb', 'CNAME', 'README.md', 'vendor']
github:
  repo:              https://github.com/alan-qiu/alan-qiu.github.io

# About/contact
author:
  name:              Alan Qiu
  url:               https://github.com/alan-qiu
  email:             alan.qiu@outlook.com

# Custom vars
version:             1.2.0
